// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UPtel.Data;

namespace UPtel.Migrations
{
    [DbContext(typeof(UPtelContext))]
    [Migration("20210319174243_Posicao")]
    partial class Posicao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UPtel.Models.Canais", b =>
                {
                    b.Property<int>("CanaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NomeCanal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CanaisId");

                    b.ToTable("Canais");
                });

            modelBuilder.Entity("UPtel.Models.ClientesViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CartaoCidadao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiogoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<int>("Desconto")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoPromocao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistritoNomeDistritoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtensaoCodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Fidelizacao")
                        .HasColumnType("int");

                    b.Property<byte[]>("Fotografia")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetFixaPacote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetMovelPacote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFuncionario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePacote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePromocao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroContribuinte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerosAssociados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoContrato")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrecoPacote")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PromocaoCanais")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonePacote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telemovel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelemovelPacote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelevisaoPacote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TempoPromocao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistritoNomeDistritoId");

                    b.ToTable("ClientesViewModel");
                });

            modelBuilder.Entity("UPtel.Models.ContratoPromoNetFixa", b =>
                {
                    b.Property<int>("ContratoPromoNetFixaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContratoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PromoNetFixaId")
                        .HasColumnType("int");

                    b.HasKey("ContratoPromoNetFixaId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("PromoNetFixaId");

                    b.ToTable("ContratoPromoNetFixa");
                });

            modelBuilder.Entity("UPtel.Models.ContratoPromoNetMovel", b =>
                {
                    b.Property<int>("ContratoPromoNetMovelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContratoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PromoNetMovelId")
                        .HasColumnType("int");

                    b.HasKey("ContratoPromoNetMovelId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("PromoNetMovelId");

                    b.ToTable("ContratoPromoNetMovel");
                });

            modelBuilder.Entity("UPtel.Models.ContratoPromoTelefone", b =>
                {
                    b.Property<int>("ContratoPromoTelefoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContratoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PromoTelefoneId")
                        .HasColumnType("int");

                    b.HasKey("ContratoPromoTelefoneId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("PromoTelefoneId");

                    b.ToTable("ContratoPromoTelefone");
                });

            modelBuilder.Entity("UPtel.Models.ContratoPromoTelemovel", b =>
                {
                    b.Property<int>("ContratoPromoTelemovelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContratoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PromoTelemovelId")
                        .HasColumnType("int");

                    b.HasKey("ContratoPromoTelemovelId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("PromoTelemovelId");

                    b.ToTable("ContratoPromoTelemovel");
                });

            modelBuilder.Entity("UPtel.Models.ContratoPromoTelevisao", b =>
                {
                    b.Property<int>("ContratoTelevisaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContratoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PromoTelevisaoId")
                        .HasColumnType("int");

                    b.HasKey("ContratoTelevisaoId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("PromoTelevisaoId");

                    b.ToTable("ContratoPromoTelevisao");
                });

            modelBuilder.Entity("UPtel.Models.Contratos", b =>
                {
                    b.Property<int>("ContratoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientesViewModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("EdicaoCliente")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("Fidelizacao")
                        .HasColumnType("int");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Numeros")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PacoteId")
                        .HasColumnType("int");

                    b.Property<int?>("Posicao")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoContrato")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ContratoId");

                    b.HasIndex("ClientesViewModelId");

                    b.HasIndex(new[] { "ClienteId" }, "IX_Contratos_ClienteId");

                    b.HasIndex(new[] { "FuncionarioId" }, "IX_Contratos_FuncionarioId");

                    b.HasIndex(new[] { "PacoteId" }, "IX_Contratos_PacoteId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("UPtel.Models.Distrito", b =>
                {
                    b.Property<int>("DistritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DistritoNome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DistritoId")
                        .HasName("PK_DistritoNome");

                    b.ToTable("Distrito");
                });

            modelBuilder.Entity("UPtel.Models.NetFixa", b =>
                {
                    b.Property<int>("NetFixaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Limite")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Notas")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecoNetFixa")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TipoConexao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Velocidade")
                        .HasColumnType("int");

                    b.HasKey("NetFixaId");

                    b.ToTable("NetFixa");
                });

            modelBuilder.Entity("UPtel.Models.NetMovel", b =>
                {
                    b.Property<int>("NetMovelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Limite")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Notas")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecoNetMovel")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("NetMovelId");

                    b.ToTable("NetMovel");
                });

            modelBuilder.Entity("UPtel.Models.OperadorViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CartaoCidadao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiogoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistritoNomeDistritoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtensaoCodigoPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Fotografia")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Morada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeOperador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroContribuinte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telemovel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistritoNomeDistritoId");

                    b.ToTable("OperadorViewModel");
                });

            modelBuilder.Entity("UPtel.Models.PacoteCanais", b =>
                {
                    b.Property<int>("PacoteCanalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CanaisId")
                        .HasColumnType("int");

                    b.Property<int>("TelevisaoId")
                        .HasColumnType("int");

                    b.HasKey("PacoteCanalId");

                    b.HasIndex("CanaisId");

                    b.HasIndex("TelevisaoId");

                    b.ToTable("PacoteCanais");
                });

            modelBuilder.Entity("UPtel.Models.Pacotes", b =>
                {
                    b.Property<int>("PacoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NetIfixaId")
                        .HasColumnType("int")
                        .HasColumnName("NetIFixaId");

                    b.Property<int?>("NetMovelId")
                        .HasColumnType("int");

                    b.Property<string>("NomePacote")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrecoTotal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("TelefoneId")
                        .HasColumnType("int");

                    b.Property<int?>("TelemovelId")
                        .HasColumnType("int");

                    b.Property<int?>("TelevisaoId")
                        .HasColumnType("int");

                    b.HasKey("PacoteId");

                    b.HasIndex("NetIfixaId");

                    b.HasIndex("NetMovelId");

                    b.HasIndex("TelefoneId");

                    b.HasIndex("TelemovelId");

                    b.HasIndex("TelevisaoId");

                    b.ToTable("Pacotes");
                });

            modelBuilder.Entity("UPtel.Models.PromoNetFixa", b =>
                {
                    b.Property<int>("PromoNetFixaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DescontoPrecoTotal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Limite")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Velocidade")
                        .HasColumnType("int");

                    b.HasKey("PromoNetFixaId");

                    b.ToTable("PromoNetFixa");
                });

            modelBuilder.Entity("UPtel.Models.PromoNetMovel", b =>
                {
                    b.Property<int>("PromoNetMovelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DescontoPrecoTotal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Limite")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PromoNetMovelId");

                    b.ToTable("PromoNetMovel");
                });

            modelBuilder.Entity("UPtel.Models.PromoTelefone", b =>
                {
                    b.Property<int>("PromoTelefoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DescontoMinInternacional")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("DescontoMinNacional")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("DescontoPrecoTotal")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Limite")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PromoTelefoneId");

                    b.ToTable("PromoTelefone");
                });

            modelBuilder.Entity("UPtel.Models.PromoTelemovel", b =>
                {
                    b.Property<int>("PromoTelemovelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DecontoPrecoMMS")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("DecontoPrecoMinInternacional")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("DecontoPrecoMinNacional")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("DecontoPrecoSMS")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("DecontoPrecoTotal")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("LimiteMinutos")
                        .HasColumnType("int");

                    b.Property<int>("LimiteSMS")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PromoTelemovelId");

                    b.ToTable("PromoTelemovel");
                });

            modelBuilder.Entity("UPtel.Models.PromoTelevisao", b =>
                {
                    b.Property<int>("PromoTelevisaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CanaisGratis")
                        .HasColumnType("int");

                    b.Property<decimal>("DescontoPrecoTotal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PromoTelevisaoId");

                    b.ToTable("PromoTelevisao");
                });

            modelBuilder.Entity("UPtel.Models.Reclamacao", b =>
                {
                    b.Property<int>("ReclamacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Assunto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriçao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("bit");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("ReclamacaoId");

                    b.HasIndex("UsersId");

                    b.ToTable("Reclamacao");
                });

            modelBuilder.Entity("UPtel.Models.Telefone", b =>
                {
                    b.Property<int>("TelefoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Limite")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<decimal>("PrecoMinutoInternacional")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("PrecoMinutoNacional")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("PrecoPacoteTelefone")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("TelefoneId");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("UPtel.Models.Telemovel", b =>
                {
                    b.Property<int>("TelemovelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LimiteMinutos")
                        .HasColumnType("int");

                    b.Property<int>("LimiteSms")
                        .HasColumnType("int")
                        .HasColumnName("LimiteSMS");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<decimal>("PrecoMinutoInternacional")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("PrecoMinutoNacional")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("PrecoMms")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("PrecoMMS");

                    b.Property<decimal>("PrecoPacoteTelemovel")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrecoSms")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("PrecoSMS");

                    b.HasKey("TelemovelId");

                    b.ToTable("Telemovel");
                });

            modelBuilder.Entity("UPtel.Models.Televisao", b =>
                {
                    b.Property<int>("TelevisaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PrecoPacoteTelevisao")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("TelevisaoId");

                    b.ToTable("Televisao");
                });

            modelBuilder.Entity("UPtel.Models.UserType", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TipoId")
                        .HasName("PK_TipoClientes");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("UPtel.Models.Users", b =>
                {
                    b.Property<int>("UsersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CartaoCidadao")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("CodigoPostalExt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValueSql("(N'')");

                    b.Property<string>("Contribuinte")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("date");

                    b.Property<int>("DistritoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Fotografia")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Iban")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IBAN");

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Telemovel")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("UsersId");

                    b.HasIndex("DistritoId");

                    b.HasIndex(new[] { "CartaoCidadao" }, "IX_CartaoCidadaoClientes")
                        .IsUnique()
                        .HasFilter("[CartaoCidadao] IS NOT NULL");

                    b.HasIndex(new[] { "TipoId" }, "IX_Clientes_TipoClienteId");

                    b.HasIndex(new[] { "Contribuinte" }, "IX_ContribuinteClientes")
                        .IsUnique();

                    b.HasIndex(new[] { "Nome" }, "IX_Nome_Users");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UPtel.Models.ClientesViewModel", b =>
                {
                    b.HasOne("UPtel.Models.Distrito", "DistritoNome")
                        .WithMany()
                        .HasForeignKey("DistritoNomeDistritoId");

                    b.Navigation("DistritoNome");
                });

            modelBuilder.Entity("UPtel.Models.ContratoPromoNetFixa", b =>
                {
                    b.HasOne("UPtel.Models.Contratos", "Contratos")
                        .WithMany("ContratoPromoNetFixa")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPtel.Models.PromoNetFixa", "PromoNetFixa")
                        .WithMany("ContratoPromoNetFixa")
                        .HasForeignKey("PromoNetFixaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contratos");

                    b.Navigation("PromoNetFixa");
                });

            modelBuilder.Entity("UPtel.Models.ContratoPromoNetMovel", b =>
                {
                    b.HasOne("UPtel.Models.Contratos", "Contratos")
                        .WithMany("ContratoPromoNetMovel")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPtel.Models.PromoNetMovel", "PromoNetMovel")
                        .WithMany("ContratoPromoNetMovel")
                        .HasForeignKey("PromoNetMovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contratos");

                    b.Navigation("PromoNetMovel");
                });

            modelBuilder.Entity("UPtel.Models.ContratoPromoTelefone", b =>
                {
                    b.HasOne("UPtel.Models.Contratos", "Contratos")
                        .WithMany("ContratoPromoTelefone")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPtel.Models.PromoTelefone", "PromoTelefone")
                        .WithMany("ContratoPromoTelefone")
                        .HasForeignKey("PromoTelefoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contratos");

                    b.Navigation("PromoTelefone");
                });

            modelBuilder.Entity("UPtel.Models.ContratoPromoTelemovel", b =>
                {
                    b.HasOne("UPtel.Models.Contratos", "Contratos")
                        .WithMany("ContratoPromoTelemovel")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPtel.Models.PromoTelemovel", "PromoTelemovel")
                        .WithMany("ContratoPromoTelemovel")
                        .HasForeignKey("PromoTelemovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contratos");

                    b.Navigation("PromoTelemovel");
                });

            modelBuilder.Entity("UPtel.Models.ContratoPromoTelevisao", b =>
                {
                    b.HasOne("UPtel.Models.Contratos", "Contratos")
                        .WithMany("ContratoPromoTelevisao")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPtel.Models.PromoTelevisao", "PromoTelevisao")
                        .WithMany("ContratoPromoTelevisao")
                        .HasForeignKey("PromoTelevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contratos");

                    b.Navigation("PromoTelevisao");
                });

            modelBuilder.Entity("UPtel.Models.Contratos", b =>
                {
                    b.HasOne("UPtel.Models.Users", "Cliente")
                        .WithMany("ContratosCliente")
                        .HasForeignKey("ClienteId")
                        .HasConstraintName("FK_Cliente_Users")
                        .IsRequired();

                    b.HasOne("UPtel.Models.ClientesViewModel", null)
                        .WithMany("ListaContratos")
                        .HasForeignKey("ClientesViewModelId");

                    b.HasOne("UPtel.Models.Users", "Funcionario")
                        .WithMany("ContratosFuncionario")
                        .HasForeignKey("FuncionarioId")
                        .HasConstraintName("FK_Funcionarios_Users")
                        .IsRequired();

                    b.HasOne("UPtel.Models.Pacotes", "Pacote")
                        .WithMany("Contratos")
                        .HasForeignKey("PacoteId")
                        .HasConstraintName("FK_Contratos_Pacotes")
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");

                    b.Navigation("Pacote");
                });

            modelBuilder.Entity("UPtel.Models.OperadorViewModel", b =>
                {
                    b.HasOne("UPtel.Models.Distrito", "DistritoNome")
                        .WithMany()
                        .HasForeignKey("DistritoNomeDistritoId");

                    b.Navigation("DistritoNome");
                });

            modelBuilder.Entity("UPtel.Models.PacoteCanais", b =>
                {
                    b.HasOne("UPtel.Models.Canais", "Canais")
                        .WithMany("PacoteCanais")
                        .HasForeignKey("CanaisId")
                        .HasConstraintName("FK_PacoteCanais_Canais")
                        .IsRequired();

                    b.HasOne("UPtel.Models.Televisao", "Televisao")
                        .WithMany("PacoteCanais")
                        .HasForeignKey("TelevisaoId")
                        .HasConstraintName("FK_PacoteCanais_Televisao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canais");

                    b.Navigation("Televisao");
                });

            modelBuilder.Entity("UPtel.Models.Pacotes", b =>
                {
                    b.HasOne("UPtel.Models.NetFixa", "NetIfixa")
                        .WithMany("Pacotes")
                        .HasForeignKey("NetIfixaId")
                        .HasConstraintName("FK_Pacotes_NetFixa1");

                    b.HasOne("UPtel.Models.NetMovel", "NetMovel")
                        .WithMany("Pacotes")
                        .HasForeignKey("NetMovelId")
                        .HasConstraintName("FK_Pacotes_NetMovel");

                    b.HasOne("UPtel.Models.Telefone", "Telefone")
                        .WithMany("Pacotes")
                        .HasForeignKey("TelefoneId")
                        .HasConstraintName("FK_Pacotes_Telemovel");

                    b.HasOne("UPtel.Models.Telemovel", "Telemovel")
                        .WithMany("Pacotes")
                        .HasForeignKey("TelemovelId")
                        .HasConstraintName("FK_Pacotes_Telefone");

                    b.HasOne("UPtel.Models.Televisao", "Televisao")
                        .WithMany("Pacotes")
                        .HasForeignKey("TelevisaoId")
                        .HasConstraintName("FK_Pacotes_Televisao1");

                    b.Navigation("NetIfixa");

                    b.Navigation("NetMovel");

                    b.Navigation("Telefone");

                    b.Navigation("Telemovel");

                    b.Navigation("Televisao");
                });

            modelBuilder.Entity("UPtel.Models.Reclamacao", b =>
                {
                    b.HasOne("UPtel.Models.Users", "Cliente")
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("UPtel.Models.Users", b =>
                {
                    b.HasOne("UPtel.Models.Distrito", "DistritoNome")
                        .WithMany("Users")
                        .HasForeignKey("DistritoId")
                        .HasConstraintName("FK_Users_Distrito")
                        .IsRequired();

                    b.HasOne("UPtel.Models.UserType", "Tipo")
                        .WithMany("Users")
                        .HasForeignKey("TipoId")
                        .HasConstraintName("FK_Users_UserType")
                        .IsRequired();

                    b.Navigation("DistritoNome");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("UPtel.Models.Canais", b =>
                {
                    b.Navigation("PacoteCanais");
                });

            modelBuilder.Entity("UPtel.Models.ClientesViewModel", b =>
                {
                    b.Navigation("ListaContratos");
                });

            modelBuilder.Entity("UPtel.Models.Contratos", b =>
                {
                    b.Navigation("ContratoPromoNetFixa");

                    b.Navigation("ContratoPromoNetMovel");

                    b.Navigation("ContratoPromoTelefone");

                    b.Navigation("ContratoPromoTelemovel");

                    b.Navigation("ContratoPromoTelevisao");
                });

            modelBuilder.Entity("UPtel.Models.Distrito", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("UPtel.Models.NetFixa", b =>
                {
                    b.Navigation("Pacotes");
                });

            modelBuilder.Entity("UPtel.Models.NetMovel", b =>
                {
                    b.Navigation("Pacotes");
                });

            modelBuilder.Entity("UPtel.Models.Pacotes", b =>
                {
                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("UPtel.Models.PromoNetFixa", b =>
                {
                    b.Navigation("ContratoPromoNetFixa");
                });

            modelBuilder.Entity("UPtel.Models.PromoNetMovel", b =>
                {
                    b.Navigation("ContratoPromoNetMovel");
                });

            modelBuilder.Entity("UPtel.Models.PromoTelefone", b =>
                {
                    b.Navigation("ContratoPromoTelefone");
                });

            modelBuilder.Entity("UPtel.Models.PromoTelemovel", b =>
                {
                    b.Navigation("ContratoPromoTelemovel");
                });

            modelBuilder.Entity("UPtel.Models.PromoTelevisao", b =>
                {
                    b.Navigation("ContratoPromoTelevisao");
                });

            modelBuilder.Entity("UPtel.Models.Telefone", b =>
                {
                    b.Navigation("Pacotes");
                });

            modelBuilder.Entity("UPtel.Models.Telemovel", b =>
                {
                    b.Navigation("Pacotes");
                });

            modelBuilder.Entity("UPtel.Models.Televisao", b =>
                {
                    b.Navigation("PacoteCanais");

                    b.Navigation("Pacotes");
                });

            modelBuilder.Entity("UPtel.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("UPtel.Models.Users", b =>
                {
                    b.Navigation("ContratosCliente");

                    b.Navigation("ContratosFuncionario");
                });
#pragma warning restore 612, 618
        }
    }
}
